/*
 *    Copyright 2025 Nacho Brito
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package es.nachobrito.vulcanodb.core.store.axon;

import es.nachobrito.vulcanodb.core.VulcanoDb;
import es.nachobrito.vulcanodb.core.document.Document;
import es.nachobrito.vulcanodb.core.document.DocumentMother;
import es.nachobrito.vulcanodb.core.query.Query;
import es.nachobrito.vulcanodb.core.result.ResultDocument;
import es.nachobrito.vulcanodb.core.util.FileUtils;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import static org.junit.jupiter.api.Assertions.*;

/**
 * @author nacho
 */
public class LeafQueryTest {
    private static Path path;
    private static AxonDataStore axon;

    // key -> a query that does not match any of the documents generated by DocumentMother
    // value -> a document that matches the query (will be returned if added to the store).
    private final Map<Query, Document> examplesWithEmptyResult = Map.of(
            VulcanoDb.queryBuilder().isEqual("This is an example of equals", "text1").build(),
            Document.builder().withStringField("text1", "This is an example of equals").build(),

            VulcanoDb.queryBuilder().contains("example of contains", "text1").build(),
            Document.builder().withStringField("text1", "This is an example of contains").build(),

            VulcanoDb.queryBuilder().startsWith("Document starting", "text1").build(),
            Document.builder().withStringField("text1", "Document starting with...").build(),

            VulcanoDb.queryBuilder().endsWith("ending with...", "text1").build(),
            Document.builder().withStringField("text1", "Document ending with...").build(),

            VulcanoDb.queryBuilder().isEqual(-1977, "number1").build(),
            Document.builder().withIntegerField("number1", -1977).build()
    );

    // key -> a query that matches some of the documents generated by DocumentMother
    // value -> a document that also matches the query, and will be returned if added to the store
    private final Map<Query, Document> examplesWithoutEmptyResult = Map.of(
            VulcanoDb.queryBuilder().isGreaterThan(-5, "number1").build(),
            Document.builder().withIntegerField("number1", -4).build(),

            VulcanoDb.queryBuilder().isGreaterThanOrEqual(-6, "number1").build(),
            Document.builder().withIntegerField("number1", -6).build(),

            VulcanoDb.queryBuilder().isLessThan(-7, "number1").build(),
            Document.builder().withIntegerField("number1", -8).build(),

            VulcanoDb.queryBuilder().isLessThanOrEqual(-7, "number1").build(),
            Document.builder().withIntegerField("number1", -7).build()
    );

    @BeforeEach
    void setup() throws IOException {
        path = Files.createTempDirectory("vulcanodb-test");
        axon = buildAxonStore();
    }

    @AfterEach
    void tearDown() throws Exception {
        axon.close();
        FileUtils.deleteRecursively(path.toFile());
    }

    private static AxonDataStore buildAxonStore() {
        var axon = AxonDataStore
                .builder()
                .withDataFolder(path)
                .build();
        var exampleDoc = Document.builder()
                .with(Map.of(
                        "number1", 0,
                        "number2", 0,
                        "text1", "",
                        "text2", ""
                )).build();

        var shape = exampleDoc.getShape();
        var docs = DocumentMother.random(shape, 100);
        var futures = docs.stream().map(axon::addAsync).toArray(CompletableFuture[]::new);
        CompletableFuture.allOf(futures).join();
        return axon;
    }

    @Test
    public void expectLeafQueriesWork() {
        examplesWithEmptyResult.forEach(LeafQueryTest::testExampleWithEmptyResult);
        examplesWithoutEmptyResult.forEach(LeafQueryTest::testExampleWithoutEmptyResult);
    }

    private static void testExampleWithoutEmptyResult(Query query, Document document) {
        //The query does not return any result before inserting the document
        var result = axon.search(query);
        assertFalse(result.getDocuments().contains(new ResultDocument(document, 1.0f)));

        //When the document is inserted, the same query returns a valid result.
        axon.add(document);
        var result2 = axon.search(query);
        assertFalse(result2.getDocuments().isEmpty());
        assertTrue(result2.getDocuments().contains(new ResultDocument(document, 1.0f)));
        assertEquals(1.0f, result2.getDocuments().getFirst().score());
    }

    private static void testExampleWithEmptyResult(Query query, Document document) {
        //The query does not return any result before inserting the document
        var result = axon.search(query);
        assertTrue(result.getDocuments().isEmpty());

        //When the document is inserted, the same query returns a valid result.
        axon.add(document);
        var result2 = axon.search(query);
        assertFalse(result2.getDocuments().isEmpty());
        assertTrue(result2.getDocuments().contains(new ResultDocument(document, 1.0f)));
        assertEquals(1.0f, result2.getDocuments().getFirst().score());
    }

    @Test
    public void expectDeletedDocumentsNotReturned() {
        var query = VulcanoDb.queryBuilder().isEqual("This is an example of equals", "text1").build();
        var document = Document.builder().withStringField("text1", "This is an example of equals").build();

        assertTrue(axon.search(query).isEmpty());
        axon.add(document);
        assertFalse(axon.search(query).isEmpty());
        axon.remove(document.id());
        assertTrue(axon.search(query).isEmpty());
    }
}
